name: 'release_package'

on:
  release:
    types: [published]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - name: install
        run: yarn install
      - name: publish
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPMJS_ACCESS_TOKEN}}
